### ISSUE TITLE
logical_type: decimal in column_options does not work

### ISSUE THREAD

**Issue by kj-9** [civitaspo/embulk-output-s3_parquet#54]
Hi,

the README says, `logical_type: decimal` is supported in `column_options`. But when I applied that option, the error occured:

```log
[DEPRECATED] Now, it is deprecated to use the "logical_type" option in this usage. Use "converted_type" instead.
[DEPRECATED] Translate {logical_type: decimal} => {converted_type: decimal}
Error: org.embulk.config.ConfigException: converted_type: decimal is not supported.
```

Although I'm not familiar with Scala nor Embulk plugins, The code below seems explicitly throws error when  `logical_type: decimal`  is given.

https://github.com/civitaspo/embulk-output-s3_parquet/blob/fd3ed47f53f159a7fdd0792a76e998d514bd55b4/src/main/scala/org/embulk/output/s3_parquet/parquet/ParquetColumnType.scala#L215-L220

So, I guess the REAME or this logic should be fixed.

p.s. Thanks for creating this very useful plugin!

**Comment by civitaspo** [comment]
@kj-9 This error may be caused by your misconfiguration. Your usage is deprecated, please use `logical_type: {name: decimal, scale: 4, precision: 5}` (This number of `scale` and `precision` is just example values, please set your required `scale` and `precision`) instead of `logical_type: decimal`.

**Comment by kj-9** [comment]
You're right, it was my fault. Sorry for bothering you and thank you for taking your time for this.
